### ISSUE TITLE
batchsize vs training iterations

### ISSUE THREAD

**Issue by TalalWasim** [OpenGVLab/efficient-video-recognition#8]
I had a couple of very basic questions.

Since you define the training length by number of iterations rather than number of epochs, does that mean increasing the batch size would require decreasing iterations accordingly to stay consistent with the 50 epoch training you report?

Because, from what I understood, 50k iterations at a batchsize of 256 would approximately mean 50 epochs (around 950 iterations/epoch for k400). Am I understanding this correctly or have I missed something?

Also, the number of workers defined is the num of workers per GPU or is it total workers across all?

Thank you in advance.

**Comment by linziyi96** [comment]
To the first question: yes, num_steps * batch_size / dataset_size =
num_epochs. It’s actually slightly more than 50 epochs but we think it will
not have a significant impact on performance. We are sorry if the wording
in the paper is causing confusion and may correct that in a future revision.

To the second question: num_workers is the number of data loading threads
per GPU.

**Comment by TalalWasim** [comment]
Thank you. That answers my question.
